language: python
python:
    - "3.6"
install:
    - pip install git+git://github.com/matplotlib/mpl_finance.git@master
    - pip install -r requirements.txt
script:
    - py.test
notifications:
    email:
        - zmcx16@gmail.com